# Generated by Django 5.0 on 2024-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('technology', 'Technology'), ('science', 'Science'), ('education', 'Education'), ('art', 'Art'), ('food', 'Food'), ('fashion', 'Fashion'), ('others', 'Others')], max_length=100),
        ),
    ]
